runtime: python39

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "your-secret-key-here-change-this"

automatic_scaling:
  min_instances: 0
  max_instances: 10

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
